export const TUNING_LABELS: Record<string, string> = {
  STANDARD: 'Standard',
  DROP_D: 'Drop D',
  DROP_C: 'Drop C',
  OPEN_G: 'Open G',
  OPEN_D: 'Open D',
  DADGAD: 'DADGAD',
}

export const KEY_LABELS: Record<string, string> = {
  E_MAJOR: 'E Major',
  A_MAJOR: 'A Major',
  C_MAJOR: 'C Major',
  D_MAJOR: 'D Major',
  A_MINOR: 'A Minor',
  E_MINOR: 'E Minor',
  D_MINOR: 'D Minor',
  G_MAJOR: 'G Major',
  B_MAJOR: 'B Major',
  F_MAJOR: 'F Major',
  Bb_MAJOR: 'B♭ Major',
  Eb_MAJOR: 'E♭ Major',
  Ab_MAJOR: 'A♭ Major',
  Db_MAJOR: 'D♭ Major',
  Gb_MAJOR: 'G♭ Major',
  B_MINOR: 'B Minor',
  F_SHARP_MINOR: 'F♯ Minor',
  C_SHARP_MINOR: 'C♯ Minor',
  G_MINOR: 'G Minor',
  C_MINOR: 'C Minor',
  F_MINOR: 'F Minor',
  Bb_MINOR: 'B♭ Minor',
}